[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["2.7", "3.11"]

[envs.default]
dependencies = [
  "khulnasoft_checks_tests_helper @ {root:uri}/../khulnasoft_checks_tests_helper",
]
platforms = [
  "windows",
]
