[env.collectors.khulnasoft-checks]
check-types = false
mypy-args = [
    "--disallow-untyped-defs",
    "--py2",
    "--install-types",
    "--non-interactive",
    "khulnasoft_checks/",
]

[[envs.default.matrix]]
python = ["2.7", "3.11"]

