[env.collectors.khulnasoft-checks]

[envs.default]
dependencies = [
  "khulnasoft_checks_tests_helper @ {root:uri}/../khulnasoft_checks_tests_helper",
]
e2e-env = false
platforms = [
  "windows",
]

[[envs.default.matrix]]
python = ["2.7", "3.11"]
