[env.collectors.khulnasoft-checks]
check-types = false
mypy-args = [
    "--py2",
    "--follow-imports silent",
    "khulnasoft_checks/dns_check",
]

[[envs.default.matrix]]
python = ["2.7", "3.11"]
