name: PR All

on:
  pull_request:
    branches:
    - master
    paths:
    - khulnasoft_checks_base/khulnasoft_checks/**
    - khulnasoft_checks_dev/khulnasoft_checks/dev/*.py
    - ddev/src/**
    - "!khulnasoft_checks_base/khulnasoft_checks/base/data/agent_requirements.in"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test-all.yml
    with:
      repo: core

      # Options
      standard: true
      test-py2: true
    secrets: inherit

  save-event:
    needs:
    - test
    if: success() || failure()

    uses: ./.github/workflows/save-event.yml

  submit-traces:
    needs:
    - test
    if: success() || failure()

    uses: ./.github/workflows/submit-traces.yml
    secrets: inherit
