name: PR

on:
  pull_request:
    paths-ignore:
    - khulnasoft_checks_base/khulnasoft_checks/**
    - khulnasoft_checks_dev/khulnasoft_checks/dev/*.py

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/pr-test.yml
    with:
      repo: core
    secrets: inherit
